version: '3.5'

x-common-variables: &common-variables
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

services:
  financial_news:
    build:
      context: ..
    image: financial_news_server
    network_mode: "host"
    command: /bin/sh -c "sleep 1 && python manage.py migrate && python manage.py runserver"
    ports:
      - "8000:8000"
    environment: *common-variables
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    restart: "always"
    hostname: redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"

  # Docker container running Postgres DB.
  postgres:
    image: postgres:14-alpine
    restart: "no"
    environment: *common-variables
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  celery_worker:
    build:
      context: ..
    image: financial_news_server
    network_mode: "host"
    environment: *common-variables
    depends_on:
      - postgres
      - redis
    command: "celery -A core worker -l INFO"
    restart: "on-failure"


  celery_beat:
    build:
      context: ..
    image: financial_news_server
    network_mode: "host"
    depends_on:
      - postgres
      - redis
      - celery_worker
    command: "celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    restart: "on-failure"

volumes:
  postgres_data: {}

networks:
  default:
    name: main_network
