version: '3.5'

services:
#  financial_news:
#    image: ???
#    TODO

  # Docker container running Postgres DB.
  postgres:
    image: postgres:14-alpine
    restart: "no"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

#volumes:
#  postgres_data: {}

networks:
  default:
    name: main_network
